#############################################################################
# Makefile for building: testARM_API
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  testARM_API.pro
# Template: app
# Command: /home/dau64/ARM_LJD/_Qt-5.5.1_static/bin/qmake -o Makefile testARM_API.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -O2 -march=armv7-a -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -O2 -march=armv7-a -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../_Qt-5.5.1_static/include -I../_Qt-5.5.1_static/include/QtCore -I. -I../_Qt-5.5.1_static/mkspecs/linux-arm-gnueabi-g++
QMAKE         = /home/dau64/ARM_LJD/_Qt-5.5.1_static/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = testARM_API1.0.0
DISTDIR = /home/dau64/ARM_LJD/testARM_API/.tmp/testARM_API1.0.0
LINK          = arm-linux-g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/home/dau64/ARM_LJD/testARM_API -lEM_Middleware_Lib -lLJD_Middleware_Lib -L/home/dau64/ARM_LJD/_Qt-5.5.1_static/lib -lQt5Core -lqtpcre -lm -ldl -lrt -lpthread 
AR            = arm-linux-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-linux-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = ../_Qt-5.5.1_static/mkspecs/features/spec_pre.prf \
		../_Qt-5.5.1_static/mkspecs/common/unix.conf \
		../_Qt-5.5.1_static/mkspecs/common/linux.conf \
		../_Qt-5.5.1_static/mkspecs/common/sanitize.conf \
		../_Qt-5.5.1_static/mkspecs/common/gcc-base.conf \
		../_Qt-5.5.1_static/mkspecs/common/gcc-base-unix.conf \
		../_Qt-5.5.1_static/mkspecs/common/g++-base.conf \
		../_Qt-5.5.1_static/mkspecs/common/g++-unix.conf \
		../_Qt-5.5.1_static/mkspecs/qconfig.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_bluetooth.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_concurrent.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_concurrent_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_core.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_core_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_gui.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_gui_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimedia.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimedia_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_network.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_network_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_nfc.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_nfc_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_positioning.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_positioning_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_printsupport.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_printsupport_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_script.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_script_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_scripttools.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_scripttools_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sensors.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sensors_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_serialport.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_serialport_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sql.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sql_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_testlib.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_testlib_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_websockets.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_websockets_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_widgets.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_widgets_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_xml.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_xml_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qdds.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qicns.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qico.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qjp2.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qminimal.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qmng.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qsqlite.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtga.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtiff.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qwbmp.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qwebp.pri \
		../_Qt-5.5.1_static/mkspecs/features/qt_functions.prf \
		../_Qt-5.5.1_static/mkspecs/features/qt_config.prf \
		../_Qt-5.5.1_static/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		../_Qt-5.5.1_static/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../_Qt-5.5.1_static/mkspecs/features/exclusive_builds.prf \
		../_Qt-5.5.1_static/mkspecs/features/default_pre.prf \
		../_Qt-5.5.1_static/mkspecs/features/resolve_config.prf \
		../_Qt-5.5.1_static/mkspecs/features/default_post.prf \
		../_Qt-5.5.1_static/mkspecs/features/c++11.prf \
		../_Qt-5.5.1_static/mkspecs/features/warn_on.prf \
		../_Qt-5.5.1_static/mkspecs/features/qt.prf \
		../_Qt-5.5.1_static/mkspecs/features/resources.prf \
		../_Qt-5.5.1_static/mkspecs/features/moc.prf \
		../_Qt-5.5.1_static/mkspecs/features/unix/thread.prf \
		../_Qt-5.5.1_static/mkspecs/features/testcase_targets.prf \
		../_Qt-5.5.1_static/mkspecs/features/exceptions.prf \
		../_Qt-5.5.1_static/mkspecs/features/yacc.prf \
		../_Qt-5.5.1_static/mkspecs/features/lex.prf \
		testARM_API.pro libs_emfuture_odm.h \
		libs_ljd_odm.h main.cpp
QMAKE_TARGET  = testARM_API
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = testARM_API


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): /home/dau64/ARM_LJD/_Qt-5.5.1_static/lib/libQt5Core.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: testARM_API.pro ../_Qt-5.5.1_static/mkspecs/linux-arm-gnueabi-g++/qmake.conf ../_Qt-5.5.1_static/mkspecs/features/spec_pre.prf \
		../_Qt-5.5.1_static/mkspecs/common/unix.conf \
		../_Qt-5.5.1_static/mkspecs/common/linux.conf \
		../_Qt-5.5.1_static/mkspecs/common/sanitize.conf \
		../_Qt-5.5.1_static/mkspecs/common/gcc-base.conf \
		../_Qt-5.5.1_static/mkspecs/common/gcc-base-unix.conf \
		../_Qt-5.5.1_static/mkspecs/common/g++-base.conf \
		../_Qt-5.5.1_static/mkspecs/common/g++-unix.conf \
		../_Qt-5.5.1_static/mkspecs/qconfig.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_bluetooth.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_concurrent.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_concurrent_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_core.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_core_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_gui.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_gui_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimedia.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimedia_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_network.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_network_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_nfc.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_nfc_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_positioning.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_positioning_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_printsupport.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_printsupport_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_script.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_script_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_scripttools.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_scripttools_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sensors.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sensors_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_serialport.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_serialport_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sql.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sql_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_testlib.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_testlib_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_websockets.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_websockets_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_widgets.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_widgets_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_xml.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_lib_xml_private.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qdds.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qicns.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qico.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qjp2.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qminimal.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qmng.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qsqlite.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtga.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtiff.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qwbmp.pri \
		../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qwebp.pri \
		../_Qt-5.5.1_static/mkspecs/features/qt_functions.prf \
		../_Qt-5.5.1_static/mkspecs/features/qt_config.prf \
		../_Qt-5.5.1_static/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		../_Qt-5.5.1_static/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../_Qt-5.5.1_static/mkspecs/features/exclusive_builds.prf \
		../_Qt-5.5.1_static/mkspecs/features/default_pre.prf \
		../_Qt-5.5.1_static/mkspecs/features/resolve_config.prf \
		../_Qt-5.5.1_static/mkspecs/features/default_post.prf \
		../_Qt-5.5.1_static/mkspecs/features/c++11.prf \
		../_Qt-5.5.1_static/mkspecs/features/warn_on.prf \
		../_Qt-5.5.1_static/mkspecs/features/qt.prf \
		../_Qt-5.5.1_static/mkspecs/features/resources.prf \
		../_Qt-5.5.1_static/mkspecs/features/moc.prf \
		../_Qt-5.5.1_static/mkspecs/features/unix/thread.prf \
		../_Qt-5.5.1_static/mkspecs/features/testcase_targets.prf \
		../_Qt-5.5.1_static/mkspecs/features/exceptions.prf \
		../_Qt-5.5.1_static/mkspecs/features/yacc.prf \
		../_Qt-5.5.1_static/mkspecs/features/lex.prf \
		testARM_API.pro \
		/home/dau64/ARM_LJD/_Qt-5.5.1_static/lib/libQt5Core.prl
	$(QMAKE) -o Makefile testARM_API.pro
../_Qt-5.5.1_static/mkspecs/features/spec_pre.prf:
../_Qt-5.5.1_static/mkspecs/common/unix.conf:
../_Qt-5.5.1_static/mkspecs/common/linux.conf:
../_Qt-5.5.1_static/mkspecs/common/sanitize.conf:
../_Qt-5.5.1_static/mkspecs/common/gcc-base.conf:
../_Qt-5.5.1_static/mkspecs/common/gcc-base-unix.conf:
../_Qt-5.5.1_static/mkspecs/common/g++-base.conf:
../_Qt-5.5.1_static/mkspecs/common/g++-unix.conf:
../_Qt-5.5.1_static/mkspecs/qconfig.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_bluetooth.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_bluetooth_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_bootstrap_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_concurrent.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_concurrent_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_core.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_core_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_gui.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_gui_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimedia.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimedia_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimediawidgets.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_network.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_network_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_nfc.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_nfc_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_platformsupport_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_positioning.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_positioning_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_printsupport.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_printsupport_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_script.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_script_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_scripttools.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_scripttools_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sensors.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sensors_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_serialport.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_serialport_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sql.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_sql_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_testlib.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_testlib_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_websockets.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_websockets_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_widgets.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_widgets_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_xml.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_lib_xml_private.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qdds.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qicns.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qico.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qjp2.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qlinuxfb.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qminimal.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qmng.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qoffscreen.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qsqlite.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtga.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtiff.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qwbmp.pri:
../_Qt-5.5.1_static/mkspecs/modules/qt_plugin_qwebp.pri:
../_Qt-5.5.1_static/mkspecs/features/qt_functions.prf:
../_Qt-5.5.1_static/mkspecs/features/qt_config.prf:
../_Qt-5.5.1_static/mkspecs/linux-arm-gnueabi-g++/qmake.conf:
../_Qt-5.5.1_static/mkspecs/features/spec_post.prf:
.qmake.stash:
../_Qt-5.5.1_static/mkspecs/features/exclusive_builds.prf:
../_Qt-5.5.1_static/mkspecs/features/default_pre.prf:
../_Qt-5.5.1_static/mkspecs/features/resolve_config.prf:
../_Qt-5.5.1_static/mkspecs/features/default_post.prf:
../_Qt-5.5.1_static/mkspecs/features/c++11.prf:
../_Qt-5.5.1_static/mkspecs/features/warn_on.prf:
../_Qt-5.5.1_static/mkspecs/features/qt.prf:
../_Qt-5.5.1_static/mkspecs/features/resources.prf:
../_Qt-5.5.1_static/mkspecs/features/moc.prf:
../_Qt-5.5.1_static/mkspecs/features/unix/thread.prf:
../_Qt-5.5.1_static/mkspecs/features/testcase_targets.prf:
../_Qt-5.5.1_static/mkspecs/features/exceptions.prf:
../_Qt-5.5.1_static/mkspecs/features/yacc.prf:
../_Qt-5.5.1_static/mkspecs/features/lex.prf:
testARM_API.pro:
/home/dau64/ARM_LJD/_Qt-5.5.1_static/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile testARM_API.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents libs_emfuture_odm.h libs_ljd_odm.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp ../_Qt-5.5.1_static/include/QtCore/QCoreApplication \
		../_Qt-5.5.1_static/include/QtCore/qcoreapplication.h \
		../_Qt-5.5.1_static/include/QtCore/qglobal.h \
		../_Qt-5.5.1_static/include/QtCore/qconfig.h \
		../_Qt-5.5.1_static/include/QtCore/qfeatures.h \
		../_Qt-5.5.1_static/include/QtCore/qsystemdetection.h \
		../_Qt-5.5.1_static/include/QtCore/qprocessordetection.h \
		../_Qt-5.5.1_static/include/QtCore/qcompilerdetection.h \
		../_Qt-5.5.1_static/include/QtCore/qtypeinfo.h \
		../_Qt-5.5.1_static/include/QtCore/qtypetraits.h \
		../_Qt-5.5.1_static/include/QtCore/qsysinfo.h \
		../_Qt-5.5.1_static/include/QtCore/qlogging.h \
		../_Qt-5.5.1_static/include/QtCore/qflags.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic.h \
		../_Qt-5.5.1_static/include/QtCore/qbasicatomic.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic_bootstrap.h \
		../_Qt-5.5.1_static/include/QtCore/qgenericatomic.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic_cxx11.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic_gcc.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic_msvc.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic_armv7.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic_armv6.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic_armv5.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic_ia64.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic_mips.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic_x86.h \
		../_Qt-5.5.1_static/include/QtCore/qatomic_unix.h \
		../_Qt-5.5.1_static/include/QtCore/qglobalstatic.h \
		../_Qt-5.5.1_static/include/QtCore/qmutex.h \
		../_Qt-5.5.1_static/include/QtCore/qnumeric.h \
		../_Qt-5.5.1_static/include/QtCore/qstring.h \
		../_Qt-5.5.1_static/include/QtCore/qchar.h \
		../_Qt-5.5.1_static/include/QtCore/qbytearray.h \
		../_Qt-5.5.1_static/include/QtCore/qrefcount.h \
		../_Qt-5.5.1_static/include/QtCore/qnamespace.h \
		../_Qt-5.5.1_static/include/QtCore/qarraydata.h \
		../_Qt-5.5.1_static/include/QtCore/qstringbuilder.h \
		../_Qt-5.5.1_static/include/QtCore/qobject.h \
		../_Qt-5.5.1_static/include/QtCore/qobjectdefs.h \
		../_Qt-5.5.1_static/include/QtCore/qobjectdefs_impl.h \
		../_Qt-5.5.1_static/include/QtCore/qlist.h \
		../_Qt-5.5.1_static/include/QtCore/qalgorithms.h \
		../_Qt-5.5.1_static/include/QtCore/qiterator.h \
		../_Qt-5.5.1_static/include/QtCore/qbytearraylist.h \
		../_Qt-5.5.1_static/include/QtCore/qstringlist.h \
		../_Qt-5.5.1_static/include/QtCore/qregexp.h \
		../_Qt-5.5.1_static/include/QtCore/qstringmatcher.h \
		../_Qt-5.5.1_static/include/QtCore/qcoreevent.h \
		../_Qt-5.5.1_static/include/QtCore/qscopedpointer.h \
		../_Qt-5.5.1_static/include/QtCore/qmetatype.h \
		../_Qt-5.5.1_static/include/QtCore/qvarlengtharray.h \
		../_Qt-5.5.1_static/include/QtCore/qcontainerfwd.h \
		../_Qt-5.5.1_static/include/QtCore/qisenum.h \
		../_Qt-5.5.1_static/include/QtCore/qobject_impl.h \
		../_Qt-5.5.1_static/include/QtCore/qeventloop.h \
		../_Qt-5.5.1_static/include/QtCore/QTextCodec \
		../_Qt-5.5.1_static/include/QtCore/qtextcodec.h \
		../_Qt-5.5.1_static/include/QtCore/QThread \
		../_Qt-5.5.1_static/include/QtCore/qthread.h \
		libs_emfuture_odm.h \
		../_Qt-5.5.1_static/include/QtCore/QDebug \
		../_Qt-5.5.1_static/include/QtCore/qdebug.h \
		../_Qt-5.5.1_static/include/QtCore/qhash.h \
		../_Qt-5.5.1_static/include/QtCore/qpair.h \
		../_Qt-5.5.1_static/include/QtCore/qmap.h \
		../_Qt-5.5.1_static/include/QtCore/qtextstream.h \
		../_Qt-5.5.1_static/include/QtCore/qiodevice.h \
		../_Qt-5.5.1_static/include/QtCore/qlocale.h \
		../_Qt-5.5.1_static/include/QtCore/qvariant.h \
		../_Qt-5.5.1_static/include/QtCore/qshareddata.h \
		../_Qt-5.5.1_static/include/QtCore/qvector.h \
		../_Qt-5.5.1_static/include/QtCore/qpoint.h \
		../_Qt-5.5.1_static/include/QtCore/qset.h \
		../_Qt-5.5.1_static/include/QtCore/qcontiguouscache.h \
		libs_ljd_odm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

